# helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
# helm install prometheus prometheus-community/prometheus -f prometheus-values.yaml

fullnameOverride: prometheus

server:
  persistentVolume:
    enabled: false
  service:
    type: NodePort

alertmanager:
  enabled: false

nodeExporter:
  enabled: true

pushgateway:
  enabled: false

kubeStateMetrics:
  enabled: false
