apiVersion: batch/v1
kind: Job
metadata:
  name: testjob
spec:
  parallelism: 3
  completions: 3
  template:
    spec:
      containers:
      - name: pi
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(1100)"]
      restartPolicy: Never
  backoffLimit: 4