#
# Deploy a simple web application. I created this years ago
# - but it's still a good example of something to deploy and run
#

kind: Deployment
apiVersion: apps/v1
metadata:
  name: nodeapp
  labels:
    app: nodeapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
        - name: app
          image: ghcr.io/benc-uk/nodejs-demoapp:latest-arm
          imagePullPolicy: Always
          ports:
            - containerPort: 3000

---
kind: Service
apiVersion: v1
metadata:
  name: nodeapp
spec:
  type: NodePort
  selector:
    app: nodeapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000

---
# Even if you don't have an Ingress controller, this won't cause an error
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nodeapp
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nodeapp
                port:
                  number: 3000
