#
# Example of a PersistentVolume for Grafana that uses the NFS server
# You must edit this before deploying, see the comments below
#

apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-volume
  labels:
    directory: grafana
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    # This is the path within the exported NFS volume
    path: /share01
    # WHY IP?! We can't use the service DNS name as it's resolved from the host not the pods
    # To get IP run this: kubectl get svc -n storage nfs-server -o jsonpath='{.spec.clusterIP}'
    server: 10.104.245.46
