kind: Deployment
apiVersion: apps/v1
metadata:
  name: mainframe
  labels:
    app: mainframe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mainframe
  template:
    metadata:
      labels:
        app: mainframe
    spec:
      containers:
      - name: mainframe
        image: bencuk/hercules-mvs:latest
        ports:
        - containerPort: 8038
        - containerPort: 3270
        resources:
          limits:
            cpu: 500m
            memory: 300M
          requests:
            cpu: 100m
            memory: 100M

---

kind: Service
apiVersion: v1
metadata:
  name: mainframe-terminal
spec:
  type: NodePort
  selector:
    app: mainframe
  ports:
    - protocol: TCP
      port: 3270
      targetPort: 3270
      nodePort: 31270

---

kind: Service
apiVersion: v1
metadata:
  name: mainframe-web
spec:
  type: NodePort
  selector:
    app: mainframe
  ports:
    - protocol: TCP
      port: 8038
      targetPort: 8038
      nodePort: 31038
