kind: Deployment
apiVersion: apps/v1
metadata:
  name: javaapp
  labels:
    app: javaapp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: javaapp
  template:
    metadata:
      labels:
        app: javaapp
    spec:
      containers:
      - name: app
        image: bencuk/java-demoapp:arm
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
            memory: 200M
          requests:
            cpu: 100m
            memory: 100M

---

kind: Service
apiVersion: v1
metadata:
  name: javaapp
spec:
  type: NodePort
  selector:
    app: javaapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30002

---

# kind: Ingress
# apiVersion: networking.k8s.io/v1beta1
# metadata:
#   name: nodeapp
#   # annotations:
#   #   nginx.ingress.kubernetes.io/rewrite-target: /
# spec:
#   rules:
#   - http:
#       paths:
#       - path: /
#         backend:
#           serviceName: nodeapp
#           servicePort: 80